version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: etc/api.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: etc/frontend.Dockerfile
    ports:
      - "3000:3000"
